version: '2'
services:
    jappv2-app:
        image: jappv2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jappv2-mysql:3306/jappv2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jappv2-mysql:
        extends:
            file: mysql.yml
            service: jappv2-mysql
